title: "Shashank Kirtania"
author: "Shashank Kirtania"
description: "Made with <b style=\"color: #f45;\">&lt;3</b> by 5hv5hvnk"
lang: "en"
permalink: "/:title/"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Curriculum Vitae, icon: file, url: "https://github.com/5hv5hvnk"}
  - {title: google scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=AT5hwWkAAAAJ&hl=en"}
  - {title: Github, icon: github, url: "https://github.com/5hv5hvnk"}
  - {title: Mail, icon: envelope, url: "mailto:shashankkirtania123@gmail.com"}
  - {title: linkedin, icon: linkedin, url: "https://www.linkedin.com/in/5hv5hvnk/"}


plugins:
 - jekyll-feed
