title: "Shashank Kirtania"
author: "Shashank Kirtania"
description: "Made with <b style=\"color: #f45;\">&lt;3</b> by 5hv5hvnk"
lang: "en"
permalink: "/README"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md",title: home}
  - {file: "index.md", title: about}
  - {file: "blog.md", title: blog}
  - {file: "CV.pdf", title: curriculum vitae, url: "https://5hv5hvnk.github.io/resume.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:shashankkirtania123@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/5hv5hvnk/contrast"}
  - {title: VSCO, url: "https://vsco.co/5hv5hvnk/gallery"}
  - {title: linkedin, url: "https://www.linkedin.com/in/shashank-kirtania-83835b129/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
